version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  node: circleci/node@5.0.2

jobs:
  build: 
    executor: node/default 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - run:
          name: "Print an env var stored in the Project"
          command: echo ${PROJECT_ENV_VAR}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build-image-and-push:
    working_directory: ~/ce-team-project-frontend
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker 
      - aws-ecr/build-and-push-image:
          repo: frontend
          path: "." 
          build-path: "." 
          tag: ${CIRCLE_BUILD_NUM} 
          public-registry-alias: m6p2m6g2
          public-registry: true


workflows:
  demo-app-pipeline: 
    jobs:
      - build
      - build-image-and-push:
          requires: 
            - build